import { Inter } from "next/font/google";
import "./globals.css";
import PagesAnimation from "@/components/PagesAnimation";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Omkar Thorat Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-gradient-to-b overflow-x-hidden">
          <PagesAnimation>{children}</PagesAnimation>
        </div>
      </body>
    </html>
  );
}
